project_id = "pvtidyrkkrpaopuwtmtp"

[functions.bot-register]
verify_jwt = false

[functions.bot-status]
verify_jwt = false

[functions.gazette]
verify_jwt = false

[functions.bot-claim-lookup]
verify_jwt = false

[functions.bot-verify]
verify_jwt = false